// Poistetaan KissaStaffeja
DELETE http://localhost:3003/api/blogs/667fc997a985f707586016ef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRhaU1pIiwiaWQiOiI2NjdiZjMyMGI3MjhjOWVkNTY0NzY2MzAiLCJpYXQiOjE3MTk2NTA2MjgsImV4cCI6MTcxOTY1NDIyOH0.eXIi0RNS-ScV9uBFZixPtIzZjXrSA94yx_-AqUgUM4g
