PUT http://localhost:3003/api/blogs/667fd29339573adc06d02345 
Content-Type: application/json

{
    "title": "KissaStaffeja",
    "author": "Taija Mitronen",
    "url": "www.random.fi",
    "likes": 8
} 