POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer <PUT HERE TOKEN>

{
        "title": "VauvaStaffeja",
        "author": "Testi Uuseri",
        "url": "www.vauveli.fi",
        "likes": 2
}